version: 2
project_name: q15

builds:
  - id: q15
    dir: systems/agent
    main: .
    binary: q15
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath

  - id: q15-exec-service
    dir: systems/exec-service
    main: .
    binary: q15-exec-service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath

  - id: q15-proxy-service
    dir: systems/proxy-service
    main: .
    binary: q15-proxy-service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath

archives:
  - id: q15-linux
    ids:
      - q15
      - q15-exec-service
      - q15-proxy-service
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  use: github-native
  sort: asc

release:
  draft: false
  replace_existing_draft: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"
