// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: q15/proxy/v1/proxy.proto

package proxypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeInfoRequest) Reset() {
	*x = GetRuntimeInfoRequest{}
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoRequest) ProtoMessage() {}

func (x *GetRuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_q15_proxy_v1_proxy_proto_rawDescGZIP(), []int{0}
}

type RuntimeCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCapability) Reset() {
	*x = RuntimeCapability{}
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCapability) ProtoMessage() {}

func (x *RuntimeCapability) ProtoReflect() protoreflect.Message {
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCapability.ProtoReflect.Descriptor instead.
func (*RuntimeCapability) Descriptor() ([]byte, []int) {
	return file_q15_proxy_v1_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeCapability) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetRuntimeInfoResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServiceVersion       string                 `protobuf:"bytes,1,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	AdvertiseProxyUrl    string                 `protobuf:"bytes,2,opt,name=advertise_proxy_url,json=advertiseProxyUrl,proto3" json:"advertise_proxy_url,omitempty"`
	NoProxy              string                 `protobuf:"bytes,3,opt,name=no_proxy,json=noProxy,proto3" json:"no_proxy,omitempty"`
	SetLowercaseProxyEnv bool                   `protobuf:"varint,4,opt,name=set_lowercase_proxy_env,json=setLowercaseProxyEnv,proto3" json:"set_lowercase_proxy_env,omitempty"`
	CaCertPem            []byte                 `protobuf:"bytes,5,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	EnvValues            map[string]string      `protobuf:"bytes,6,rep,name=env_values,json=envValues,proto3" json:"env_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PolicyRevision       string                 `protobuf:"bytes,7,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	Capabilities         []*RuntimeCapability   `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRuntimeInfoResponse) Reset() {
	*x = GetRuntimeInfoResponse{}
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoResponse) ProtoMessage() {}

func (x *GetRuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_proxy_v1_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_q15_proxy_v1_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuntimeInfoResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetAdvertiseProxyUrl() string {
	if x != nil {
		return x.AdvertiseProxyUrl
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetNoProxy() string {
	if x != nil {
		return x.NoProxy
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetSetLowercaseProxyEnv() bool {
	if x != nil {
		return x.SetLowercaseProxyEnv
	}
	return false
}

func (x *GetRuntimeInfoResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *GetRuntimeInfoResponse) GetEnvValues() map[string]string {
	if x != nil {
		return x.EnvValues
	}
	return nil
}

func (x *GetRuntimeInfoResponse) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetCapabilities() []*RuntimeCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_q15_proxy_v1_proxy_proto protoreflect.FileDescriptor

const file_q15_proxy_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x18q15/proxy/v1/proxy.proto\x12\fq15.proxy.v1\"\x17\n" +
	"\x15GetRuntimeInfoRequest\"A\n" +
	"\x11RuntimeCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xe3\x03\n" +
	"\x16GetRuntimeInfoResponse\x12'\n" +
	"\x0fservice_version\x18\x01 \x01(\tR\x0eserviceVersion\x12.\n" +
	"\x13advertise_proxy_url\x18\x02 \x01(\tR\x11advertiseProxyUrl\x12\x19\n" +
	"\bno_proxy\x18\x03 \x01(\tR\anoProxy\x125\n" +
	"\x17set_lowercase_proxy_env\x18\x04 \x01(\bR\x14setLowercaseProxyEnv\x12\x1e\n" +
	"\vca_cert_pem\x18\x05 \x01(\fR\tcaCertPem\x12R\n" +
	"\n" +
	"env_values\x18\x06 \x03(\v23.q15.proxy.v1.GetRuntimeInfoResponse.EnvValuesEntryR\tenvValues\x12'\n" +
	"\x0fpolicy_revision\x18\a \x01(\tR\x0epolicyRevision\x12C\n" +
	"\fcapabilities\x18\b \x03(\v2\x1f.q15.proxy.v1.RuntimeCapabilityR\fcapabilities\x1a<\n" +
	"\x0eEnvValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012k\n" +
	"\fProxyService\x12[\n" +
	"\x0eGetRuntimeInfo\x12#.q15.proxy.v1.GetRuntimeInfoRequest\x1a$.q15.proxy.v1.GetRuntimeInfoResponseB:Z8github.com/q15co/q15/libs/proxy-contract/proxypb;proxypbb\x06proto3"

var (
	file_q15_proxy_v1_proxy_proto_rawDescOnce sync.Once
	file_q15_proxy_v1_proxy_proto_rawDescData []byte
)

func file_q15_proxy_v1_proxy_proto_rawDescGZIP() []byte {
	file_q15_proxy_v1_proxy_proto_rawDescOnce.Do(func() {
		file_q15_proxy_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_q15_proxy_v1_proxy_proto_rawDesc), len(file_q15_proxy_v1_proxy_proto_rawDesc)))
	})
	return file_q15_proxy_v1_proxy_proto_rawDescData
}

var file_q15_proxy_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_q15_proxy_v1_proxy_proto_goTypes = []any{
	(*GetRuntimeInfoRequest)(nil),  // 0: q15.proxy.v1.GetRuntimeInfoRequest
	(*RuntimeCapability)(nil),      // 1: q15.proxy.v1.RuntimeCapability
	(*GetRuntimeInfoResponse)(nil), // 2: q15.proxy.v1.GetRuntimeInfoResponse
	nil,                            // 3: q15.proxy.v1.GetRuntimeInfoResponse.EnvValuesEntry
}
var file_q15_proxy_v1_proxy_proto_depIdxs = []int32{
	3, // 0: q15.proxy.v1.GetRuntimeInfoResponse.env_values:type_name -> q15.proxy.v1.GetRuntimeInfoResponse.EnvValuesEntry
	1, // 1: q15.proxy.v1.GetRuntimeInfoResponse.capabilities:type_name -> q15.proxy.v1.RuntimeCapability
	0, // 2: q15.proxy.v1.ProxyService.GetRuntimeInfo:input_type -> q15.proxy.v1.GetRuntimeInfoRequest
	2, // 3: q15.proxy.v1.ProxyService.GetRuntimeInfo:output_type -> q15.proxy.v1.GetRuntimeInfoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_q15_proxy_v1_proxy_proto_init() }
func file_q15_proxy_v1_proxy_proto_init() {
	if File_q15_proxy_v1_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_q15_proxy_v1_proxy_proto_rawDesc), len(file_q15_proxy_v1_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_q15_proxy_v1_proxy_proto_goTypes,
		DependencyIndexes: file_q15_proxy_v1_proxy_proto_depIdxs,
		MessageInfos:      file_q15_proxy_v1_proxy_proto_msgTypes,
	}.Build()
	File_q15_proxy_v1_proxy_proto = out.File
	file_q15_proxy_v1_proxy_proto_goTypes = nil
	file_q15_proxy_v1_proxy_proto_depIdxs = nil
}
