// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: q15/chat/v1/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	// SESSION_STATE_IDLE is open with no run in flight.
	SessionState_SESSION_STATE_IDLE SessionState = 1
	// SESSION_STATE_RUNNING has a run in flight.
	SessionState_SESSION_STATE_RUNNING SessionState = 2
	// SESSION_STATE_CLOSED accepts no further sends.
	SessionState_SESSION_STATE_CLOSED SessionState = 3
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_IDLE",
		2: "SESSION_STATE_RUNNING",
		3: "SESSION_STATE_CLOSED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_IDLE":        1,
		"SESSION_STATE_RUNNING":     2,
		"SESSION_STATE_CLOSED":      3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_q15_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_q15_chat_v1_chat_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED RunStatus = 0
	RunStatus_RUN_STATUS_COMPLETED   RunStatus = 1
	RunStatus_RUN_STATUS_ABORTED     RunStatus = 2
	RunStatus_RUN_STATUS_FAILED      RunStatus = 3
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_COMPLETED",
		2: "RUN_STATUS_ABORTED",
		3: "RUN_STATUS_FAILED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED": 0,
		"RUN_STATUS_COMPLETED":   1,
		"RUN_STATUS_ABORTED":     2,
		"RUN_STATUS_FAILED":      3,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_q15_chat_v1_chat_proto_enumTypes[1].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_q15_chat_v1_chat_proto_enumTypes[1]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

type GetRuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeInfoRequest) Reset() {
	*x = GetRuntimeInfoRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoRequest) ProtoMessage() {}

func (x *GetRuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

// RuntimeCapability mirrors the exec contract's capability entry.
type RuntimeCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCapability) Reset() {
	*x = RuntimeCapability{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCapability) ProtoMessage() {}

func (x *RuntimeCapability) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCapability.ProtoReflect.Descriptor instead.
func (*RuntimeCapability) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeCapability) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetRuntimeInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceVersion string                 `protobuf:"bytes,1,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	// protocol_version is this contract's own version. Bump it only for a
	// breaking change.
	ProtocolVersion int32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// head_seq is the newest allocated transcript turn sequence, the value the
	// memory head state keeps as last_seq. The 22-digit form is a zero-padded
	// filename, not a wider number. The sequence is allocated when a run starts
	// and the turn record is written when it finishes, so while a run is in
	// flight head_seq can name a turn whose file does not exist yet. A client
	// must therefore treat head_seq as a cursor bound rather than as a promise
	// that the turn is readable.
	HeadSeq int64 `protobuf:"varint,3,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	// Deliberately no directory fields. The web tier keeps no second copy of
	// anything and does not touch the transcript or media roots, so advertising
	// those paths would invite exactly the coupling this split exists to prevent.
	Capabilities  []*RuntimeCapability `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeInfoResponse) Reset() {
	*x = GetRuntimeInfoResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoResponse) ProtoMessage() {}

func (x *GetRuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuntimeInfoResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GetRuntimeInfoResponse) GetHeadSeq() int64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *GetRuntimeInfoResponse) GetCapabilities() []*RuntimeCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Session struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// chat_id is the conversation the session is bound to.
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	State         SessionState           `protobuf:"varint,3,opt,name=state,proto3,enum=q15.chat.v1.SessionState" json:"state,omitempty"`
	OpenedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

type OpenSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id selects the conversation. Empty selects the agent's default
	// conversation for this channel.
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *OpenSessionRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *OpenSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SendMessageRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// client_msg_id is the client's own identifier for this send. It is echoed
	// back so a client can match the accepted run to its optimistic message. The
	// transcript has no per-message identifier, so this is not persisted.
	ClientMsgId   string `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	// queued is true when the session was already running, so this message waits
	// its turn instead of starting a run now.
	Queued        bool     `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	Session       *Session `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *SendMessageResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type AbortRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// turn_seq names the run to abort. Zero aborts whichever run is in flight.
	TurnSeq       int64  `protobuf:"varint,2,opt,name=turn_seq,json=turnSeq,proto3" json:"turn_seq,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *AbortRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AbortRequest) GetTurnSeq() int64 {
	if x != nil {
		return x.TurnSeq
	}
	return 0
}

func (x *AbortRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *AbortResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type WatchEventsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// after_event_index resumes from a cursor.
	AfterEventIndex int64 `protobuf:"varint,2,opt,name=after_event_index,json=afterEventIndex,proto3" json:"after_event_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *WatchEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchEventsRequest) GetAfterEventIndex() int64 {
	if x != nil {
		return x.AfterEventIndex
	}
	return 0
}

type WatchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *SessionEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsResponse) Reset() {
	*x = WatchEventsResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsResponse) ProtoMessage() {}

func (x *WatchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchEventsResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *WatchEventsResponse) GetEvent() *SessionEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// SessionEvent is one item on a session's stream.
//
// event_index is the per-session monotonic counter, the same counter
// WatchSessionRequest{after_event_index} already models, and it is what a client
// acknowledges. It is not the transcript sequence: turn_seq carries that. The
// two are different numbers and conflating them is the mistake this comment
// exists to prevent.
type SessionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventIndex int64                  `protobuf:"varint,1,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// turn_seq is the durable transcript turn this event belongs to. It is zero
	// until the agent has allocated the sequence for the run.
	TurnSeq int64 `protobuf:"varint,3,opt,name=turn_seq,json=turnSeq,proto3" json:"turn_seq,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SessionEvent_SessionOpened
	//	*SessionEvent_RunStarted
	//	*SessionEvent_ModelTurnStarted
	//	*SessionEvent_ModelTurnDelta
	//	*SessionEvent_ModelReasoningDelta
	//	*SessionEvent_ToolStarted
	//	*SessionEvent_ToolFinished
	//	*SessionEvent_RunFinished
	//	*SessionEvent_RunFailed
	//	*SessionEvent_Snapshot
	//	*SessionEvent_Notice
	Event         isSessionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *SessionEvent) GetEventIndex() int64 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *SessionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SessionEvent) GetTurnSeq() int64 {
	if x != nil {
		return x.TurnSeq
	}
	return 0
}

func (x *SessionEvent) GetEvent() isSessionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SessionEvent) GetSessionOpened() *SessionOpened {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_SessionOpened); ok {
			return x.SessionOpened
		}
	}
	return nil
}

func (x *SessionEvent) GetRunStarted() *RunStarted {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *SessionEvent) GetModelTurnStarted() *ModelTurnStarted {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ModelTurnStarted); ok {
			return x.ModelTurnStarted
		}
	}
	return nil
}

func (x *SessionEvent) GetModelTurnDelta() *ModelTurnDelta {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ModelTurnDelta); ok {
			return x.ModelTurnDelta
		}
	}
	return nil
}

func (x *SessionEvent) GetModelReasoningDelta() *ModelReasoningDelta {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ModelReasoningDelta); ok {
			return x.ModelReasoningDelta
		}
	}
	return nil
}

func (x *SessionEvent) GetToolStarted() *ToolStarted {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ToolStarted); ok {
			return x.ToolStarted
		}
	}
	return nil
}

func (x *SessionEvent) GetToolFinished() *ToolFinished {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ToolFinished); ok {
			return x.ToolFinished
		}
	}
	return nil
}

func (x *SessionEvent) GetRunFinished() *RunFinished {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_RunFinished); ok {
			return x.RunFinished
		}
	}
	return nil
}

func (x *SessionEvent) GetRunFailed() *RunFailed {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_RunFailed); ok {
			return x.RunFailed
		}
	}
	return nil
}

func (x *SessionEvent) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *SessionEvent) GetNotice() *Notice {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Notice); ok {
			return x.Notice
		}
	}
	return nil
}

type isSessionEvent_Event interface {
	isSessionEvent_Event()
}

type SessionEvent_SessionOpened struct {
	SessionOpened *SessionOpened `protobuf:"bytes,4,opt,name=session_opened,json=sessionOpened,proto3,oneof"`
}

type SessionEvent_RunStarted struct {
	RunStarted *RunStarted `protobuf:"bytes,5,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type SessionEvent_ModelTurnStarted struct {
	ModelTurnStarted *ModelTurnStarted `protobuf:"bytes,6,opt,name=model_turn_started,json=modelTurnStarted,proto3,oneof"`
}

type SessionEvent_ModelTurnDelta struct {
	ModelTurnDelta *ModelTurnDelta `protobuf:"bytes,7,opt,name=model_turn_delta,json=modelTurnDelta,proto3,oneof"`
}

type SessionEvent_ModelReasoningDelta struct {
	ModelReasoningDelta *ModelReasoningDelta `protobuf:"bytes,8,opt,name=model_reasoning_delta,json=modelReasoningDelta,proto3,oneof"`
}

type SessionEvent_ToolStarted struct {
	ToolStarted *ToolStarted `protobuf:"bytes,9,opt,name=tool_started,json=toolStarted,proto3,oneof"`
}

type SessionEvent_ToolFinished struct {
	ToolFinished *ToolFinished `protobuf:"bytes,10,opt,name=tool_finished,json=toolFinished,proto3,oneof"`
}

type SessionEvent_RunFinished struct {
	RunFinished *RunFinished `protobuf:"bytes,11,opt,name=run_finished,json=runFinished,proto3,oneof"`
}

type SessionEvent_RunFailed struct {
	RunFailed *RunFailed `protobuf:"bytes,12,opt,name=run_failed,json=runFailed,proto3,oneof"`
}

type SessionEvent_Snapshot struct {
	// Snapshot is the bridge's coalesced keyframe rather than a run event: it
	// carries the full answer text accumulated so far so that a client which
	// missed deltas can recover without replaying the stream.
	Snapshot *Snapshot `protobuf:"bytes,13,opt,name=snapshot,proto3,oneof"`
}

type SessionEvent_Notice struct {
	// Notice carries anything that is not run progress, such as a resync hint.
	Notice *Notice `protobuf:"bytes,14,opt,name=notice,proto3,oneof"`
}

func (*SessionEvent_SessionOpened) isSessionEvent_Event() {}

func (*SessionEvent_RunStarted) isSessionEvent_Event() {}

func (*SessionEvent_ModelTurnStarted) isSessionEvent_Event() {}

func (*SessionEvent_ModelTurnDelta) isSessionEvent_Event() {}

func (*SessionEvent_ModelReasoningDelta) isSessionEvent_Event() {}

func (*SessionEvent_ToolStarted) isSessionEvent_Event() {}

func (*SessionEvent_ToolFinished) isSessionEvent_Event() {}

func (*SessionEvent_RunFinished) isSessionEvent_Event() {}

func (*SessionEvent_RunFailed) isSessionEvent_Event() {}

func (*SessionEvent_Snapshot) isSessionEvent_Event() {}

func (*SessionEvent_Notice) isSessionEvent_Event() {}

type SessionOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpened) Reset() {
	*x = SessionOpened{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpened) ProtoMessage() {}

func (x *SessionOpened) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpened.ProtoReflect.Descriptor instead.
func (*SessionOpened) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *SessionOpened) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RunStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStarted) Reset() {
	*x = RunStarted{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStarted) ProtoMessage() {}

func (x *RunStarted) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStarted.ProtoReflect.Descriptor instead.
func (*RunStarted) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

// ModelTurnStarted begins a new model attempt for the run. Subscribers should
// replace any answer and reasoning draft accumulated so far.
type ModelTurnStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// loop_turn is the engine's per-run loop counter, not the transcript
	// sequence.
	LoopTurn      int32  `protobuf:"varint,1,opt,name=loop_turn,json=loopTurn,proto3" json:"loop_turn,omitempty"`
	ModelRef      string `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTurnStarted) Reset() {
	*x = ModelTurnStarted{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTurnStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTurnStarted) ProtoMessage() {}

func (x *ModelTurnStarted) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTurnStarted.ProtoReflect.Descriptor instead.
func (*ModelTurnStarted) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ModelTurnStarted) GetLoopTurn() int32 {
	if x != nil {
		return x.LoopTurn
	}
	return 0
}

func (x *ModelTurnStarted) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

type ModelTurnDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTurnDelta) Reset() {
	*x = ModelTurnDelta{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTurnDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTurnDelta) ProtoMessage() {}

func (x *ModelTurnDelta) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTurnDelta.ProtoReflect.Descriptor instead.
func (*ModelTurnDelta) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ModelTurnDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ModelReasoningDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelReasoningDelta) Reset() {
	*x = ModelReasoningDelta{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelReasoningDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelReasoningDelta) ProtoMessage() {}

func (x *ModelReasoningDelta) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelReasoningDelta.ProtoReflect.Descriptor instead.
func (*ModelReasoningDelta) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *ModelReasoningDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// arguments is the raw JSON argument object, deliberately unparsed.
	Arguments     string `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ToolStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *ToolCall              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStarted) Reset() {
	*x = ToolStarted{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStarted) ProtoMessage() {}

func (x *ToolStarted) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStarted.ProtoReflect.Descriptor instead.
func (*ToolStarted) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *ToolStarted) GetCall() *ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

type ToolFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *ToolCall              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFinished) Reset() {
	*x = ToolFinished{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFinished) ProtoMessage() {}

func (x *ToolFinished) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFinished.ProtoReflect.Descriptor instead.
func (*ToolFinished) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *ToolFinished) GetCall() *ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *ToolFinished) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolFinished) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type RunFinished struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// full_text is the complete final answer text. A terminal event always
	// carries it, including when the run was cancelled, so that one message is
	// enough for a client to recover from any missed frames.
	FullText      string    `protobuf:"bytes,1,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	ModelRef      string    `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	Status        RunStatus `protobuf:"varint,3,opt,name=status,proto3,enum=q15.chat.v1.RunStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFinished) Reset() {
	*x = RunFinished{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinished) ProtoMessage() {}

func (x *RunFinished) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinished.ProtoReflect.Descriptor instead.
func (*RunFinished) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *RunFinished) GetFullText() string {
	if x != nil {
		return x.FullText
	}
	return ""
}

func (x *RunFinished) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *RunFinished) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

type RunFailed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// full_text is whatever text the run produced before it failed. It may be
	// empty.
	FullText      string    `protobuf:"bytes,1,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	Error         string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        RunStatus `protobuf:"varint,3,opt,name=status,proto3,enum=q15.chat.v1.RunStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailed) Reset() {
	*x = RunFailed{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailed) ProtoMessage() {}

func (x *RunFailed) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailed.ProtoReflect.Descriptor instead.
func (*RunFailed) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *RunFailed) GetFullText() string {
	if x != nil {
		return x.FullText
	}
	return ""
}

func (x *RunFailed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunFailed) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the full answer text accumulated so far for the in-flight run.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *Snapshot) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{24}
}

func (x *Notice) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Notice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListTurnsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// after_seq returns turns strictly older than this sequence, so a client
	// pages backwards by passing the oldest seq it already holds. Zero starts at
	// the newest turn.
	AfterSeq int64 `protobuf:"varint,1,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	// limit caps the page. Zero selects the server default; the server caps the
	// value at 500.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsRequest) Reset() {
	*x = ListTurnsRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsRequest) ProtoMessage() {}

func (x *ListTurnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsRequest.ProtoReflect.Descriptor instead.
func (*ListTurnsRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{25}
}

func (x *ListTurnsRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ListTurnsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTurnsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// turns is newest first.
	Turns []*Turn `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	// head_seq is the newest allocated transcript turn sequence.
	HeadSeq int64 `protobuf:"varint,2,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	// has_more reports whether turns older than this page still exist.
	HasMore       bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsResponse) Reset() {
	*x = ListTurnsResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsResponse) ProtoMessage() {}

func (x *ListTurnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsResponse.ProtoReflect.Descriptor instead.
func (*ListTurnsResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{26}
}

func (x *ListTurnsResponse) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

func (x *ListTurnsResponse) GetHeadSeq() int64 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *ListTurnsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Turn is one durable transcript turn.
//
// A turn record is written exactly once, when its run has finished, so every
// turn a caller can read is complete and immutable. There is deliberately no
// in-progress flag: the in-flight run owns a sequence that has no record yet,
// which is why head_seq and the newest readable turn can differ by one.
type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{27}
}

func (x *Turn) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Turn) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Turn) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Message is one canonical transcript message.
//
// Message identity is (turn seq, message ordinal, part ordinal). The transcript
// has no per-message identifier, so the ordinals are the identity.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ordinal int32                  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// role mirrors conversation.Role verbatim: "system", "user", "assistant" or
	// "tool". It is a string rather than an enum on purpose. The canonical
	// vocabulary is owned by the conversation package, and a proto enum would
	// need a translation table and would reject a kind added there.
	Role          string         `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Parts         []*MessagePart `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{28}
}

func (x *Message) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*MessagePart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// MessagePart mirrors conversation.Part, which is one deliberately flat type
// discriminated by part_type: fields that do not apply to the current part are
// empty, exactly as in the canonical model. The same string-versus-enum rule
// applies to part_type, media_kind and disposition.
type MessagePart struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ordinal int32                  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// part_type mirrors conversation.PartType: "text", "media", "reasoning",
	// "tool_call" or "tool_result".
	PartType string `protobuf:"bytes,2,opt,name=part_type,json=partType,proto3" json:"part_type,omitempty"`
	// text carries both text and reasoning parts.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// disposition mirrors conversation.TextDisposition: "commentary" or "final".
	Disposition string `protobuf:"bytes,4,opt,name=disposition,proto3" json:"disposition,omitempty"`
	// media_kind and media_ref carry media parts. media_kind mirrors
	// conversation.MediaKind.
	MediaKind string `protobuf:"bytes,5,opt,name=media_kind,json=mediaKind,proto3" json:"media_kind,omitempty"`
	MediaRef  string `protobuf:"bytes,6,opt,name=media_ref,json=mediaRef,proto3" json:"media_ref,omitempty"`
	// tool_call carries tool_call parts.
	ToolCall *ToolCall `protobuf:"bytes,7,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	// tool_call_id, content and is_error carry tool_result parts.
	ToolCallId    string `protobuf:"bytes,8,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Content       string `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool   `protobuf:"varint,10,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePart) Reset() {
	*x = MessagePart{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePart) ProtoMessage() {}

func (x *MessagePart) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePart.ProtoReflect.Descriptor instead.
func (*MessagePart) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{29}
}

func (x *MessagePart) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *MessagePart) GetPartType() string {
	if x != nil {
		return x.PartType
	}
	return ""
}

func (x *MessagePart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessagePart) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *MessagePart) GetMediaKind() string {
	if x != nil {
		return x.MediaKind
	}
	return ""
}

func (x *MessagePart) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *MessagePart) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *MessagePart) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *MessagePart) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessagePart) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{30}
}

type DeliverResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text   string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// queued_at is when the agent produced the message, not when the bridge
	// forwarded it.
	QueuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{31}
}

func (x *DeliverResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeliverResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DeliverResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

type BrowserPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Binding       string                 `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	Frame         []byte                 `protobuf:"bytes,3,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserPacket) Reset() {
	*x = BrowserPacket{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserPacket) ProtoMessage() {}

func (x *BrowserPacket) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserPacket.ProtoReflect.Descriptor instead.
func (*BrowserPacket) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{32}
}

func (x *BrowserPacket) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *BrowserPacket) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *BrowserPacket) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

type BrowserHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       string                 `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AfterSeq      int64                  `protobuf:"varint,3,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserHistoryRequest) Reset() {
	*x = BrowserHistoryRequest{}
	mi := &file_q15_chat_v1_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserHistoryRequest) ProtoMessage() {}

func (x *BrowserHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_chat_v1_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserHistoryRequest.ProtoReflect.Descriptor instead.
func (*BrowserHistoryRequest) Descriptor() ([]byte, []int) {
	return file_q15_chat_v1_chat_proto_rawDescGZIP(), []int{33}
}

func (x *BrowserHistoryRequest) GetBinding() string {
	if x != nil {
		return x.Binding
	}
	return ""
}

func (x *BrowserHistoryRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *BrowserHistoryRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *BrowserHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_q15_chat_v1_chat_proto protoreflect.FileDescriptor

const file_q15_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x16q15/chat/v1/chat.proto\x12\vq15.chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetRuntimeInfoRequest\"A\n" +
	"\x11RuntimeCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xcb\x01\n" +
	"\x16GetRuntimeInfoResponse\x12'\n" +
	"\x0fservice_version\x18\x01 \x01(\tR\x0eserviceVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\x12\x19\n" +
	"\bhead_seq\x18\x03 \x01(\x03R\aheadSeq\x12B\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x1e.q15.chat.v1.RuntimeCapabilityR\fcapabilities\"\xab\x01\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.q15.chat.v1.SessionStateR\x05state\x127\n" +
	"\topened_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bopenedAt\"-\n" +
	"\x12OpenSessionRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"E\n" +
	"\x13OpenSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.chat.v1.SessionR\asession\"k\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x81\x01\n" +
	"\x13SendMessageResponse\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\x12.\n" +
	"\asession\x18\x03 \x01(\v2\x14.q15.chat.v1.SessionR\asession\"`\n" +
	"\fAbortRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bturn_seq\x18\x02 \x01(\x03R\aturnSeq\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"?\n" +
	"\rAbortResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.chat.v1.SessionR\asession\"_\n" +
	"\x12WatchEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11after_event_index\x18\x02 \x01(\x03R\x0fafterEventIndex\"F\n" +
	"\x13WatchEventsResponse\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.q15.chat.v1.SessionEventR\x05event\"\xde\x06\n" +
	"\fSessionEvent\x12\x1f\n" +
	"\vevent_index\x18\x01 \x01(\x03R\n" +
	"eventIndex\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\bturn_seq\x18\x03 \x01(\x03R\aturnSeq\x12C\n" +
	"\x0esession_opened\x18\x04 \x01(\v2\x1a.q15.chat.v1.SessionOpenedH\x00R\rsessionOpened\x12:\n" +
	"\vrun_started\x18\x05 \x01(\v2\x17.q15.chat.v1.RunStartedH\x00R\n" +
	"runStarted\x12M\n" +
	"\x12model_turn_started\x18\x06 \x01(\v2\x1d.q15.chat.v1.ModelTurnStartedH\x00R\x10modelTurnStarted\x12G\n" +
	"\x10model_turn_delta\x18\a \x01(\v2\x1b.q15.chat.v1.ModelTurnDeltaH\x00R\x0emodelTurnDelta\x12V\n" +
	"\x15model_reasoning_delta\x18\b \x01(\v2 .q15.chat.v1.ModelReasoningDeltaH\x00R\x13modelReasoningDelta\x12=\n" +
	"\ftool_started\x18\t \x01(\v2\x18.q15.chat.v1.ToolStartedH\x00R\vtoolStarted\x12@\n" +
	"\rtool_finished\x18\n" +
	" \x01(\v2\x19.q15.chat.v1.ToolFinishedH\x00R\ftoolFinished\x12=\n" +
	"\frun_finished\x18\v \x01(\v2\x18.q15.chat.v1.RunFinishedH\x00R\vrunFinished\x127\n" +
	"\n" +
	"run_failed\x18\f \x01(\v2\x16.q15.chat.v1.RunFailedH\x00R\trunFailed\x123\n" +
	"\bsnapshot\x18\r \x01(\v2\x15.q15.chat.v1.SnapshotH\x00R\bsnapshot\x12-\n" +
	"\x06notice\x18\x0e \x01(\v2\x13.q15.chat.v1.NoticeH\x00R\x06noticeB\a\n" +
	"\x05event\".\n" +
	"\rSessionOpened\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\f\n" +
	"\n" +
	"RunStarted\"L\n" +
	"\x10ModelTurnStarted\x12\x1b\n" +
	"\tloop_turn\x18\x01 \x01(\x05R\bloopTurn\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\"&\n" +
	"\x0eModelTurnDelta\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"+\n" +
	"\x13ModelReasoningDelta\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"L\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"8\n" +
	"\vToolStarted\x12)\n" +
	"\x04call\x18\x01 \x01(\v2\x15.q15.chat.v1.ToolCallR\x04call\"l\n" +
	"\fToolFinished\x12)\n" +
	"\x04call\x18\x01 \x01(\v2\x15.q15.chat.v1.ToolCallR\x04call\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"w\n" +
	"\vRunFinished\x12\x1b\n" +
	"\tfull_text\x18\x01 \x01(\tR\bfullText\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.q15.chat.v1.RunStatusR\x06status\"n\n" +
	"\tRunFailed\x12\x1b\n" +
	"\tfull_text\x18\x01 \x01(\tR\bfullText\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.q15.chat.v1.RunStatusR\x06status\"\x1e\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"0\n" +
	"\x06Notice\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"E\n" +
	"\x10ListTurnsRequest\x12\x1b\n" +
	"\tafter_seq\x18\x01 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"r\n" +
	"\x11ListTurnsResponse\x12'\n" +
	"\x05turns\x18\x01 \x03(\v2\x11.q15.chat.v1.TurnR\x05turns\x12\x19\n" +
	"\bhead_seq\x18\x02 \x01(\x03R\aheadSeq\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x85\x01\n" +
	"\x04Turn\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x120\n" +
	"\bmessages\x18\x03 \x03(\v2\x14.q15.chat.v1.MessageR\bmessages\"g\n" +
	"\aMessage\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12.\n" +
	"\x05parts\x18\x03 \x03(\v2\x18.q15.chat.v1.MessagePartR\x05parts\"\xc1\x02\n" +
	"\vMessagePart\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x1b\n" +
	"\tpart_type\x18\x02 \x01(\tR\bpartType\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12 \n" +
	"\vdisposition\x18\x04 \x01(\tR\vdisposition\x12\x1d\n" +
	"\n" +
	"media_kind\x18\x05 \x01(\tR\tmediaKind\x12\x1b\n" +
	"\tmedia_ref\x18\x06 \x01(\tR\bmediaRef\x122\n" +
	"\ttool_call\x18\a \x01(\v2\x15.q15.chat.v1.ToolCallR\btoolCall\x12 \n" +
	"\ftool_call_id\x18\b \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\n" +
	" \x01(\bR\aisError\"\x10\n" +
	"\x0eDeliverRequest\"w\n" +
	"\x0fDeliverResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x127\n" +
	"\tqueued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\"]\n" +
	"\rBrowserPacket\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x18\n" +
	"\abinding\x18\x02 \x01(\tR\abinding\x12\x14\n" +
	"\x05frame\x18\x03 \x01(\fR\x05frame\"\x83\x01\n" +
	"\x15BrowserHistoryRequest\x12\x18\n" +
	"\abinding\x18\x01 \x01(\tR\abinding\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tafter_seq\x18\x03 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit*z\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATE_CLOSED\x10\x03*p\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_ABORTED\x10\x02\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x032\xd4\x05\n" +
	"\vChatService\x12L\n" +
	"\x0eBrowserChannel\x12\x1a.q15.chat.v1.BrowserPacket\x1a\x1a.q15.chat.v1.BrowserPacket(\x010\x01\x12P\n" +
	"\x0eBrowserHistory\x12\".q15.chat.v1.BrowserHistoryRequest\x1a\x1a.q15.chat.v1.BrowserPacket\x12Y\n" +
	"\x0eGetRuntimeInfo\x12\".q15.chat.v1.GetRuntimeInfoRequest\x1a#.q15.chat.v1.GetRuntimeInfoResponse\x12P\n" +
	"\vOpenSession\x12\x1f.q15.chat.v1.OpenSessionRequest\x1a .q15.chat.v1.OpenSessionResponse\x12P\n" +
	"\vSendMessage\x12\x1f.q15.chat.v1.SendMessageRequest\x1a .q15.chat.v1.SendMessageResponse\x12>\n" +
	"\x05Abort\x12\x19.q15.chat.v1.AbortRequest\x1a\x1a.q15.chat.v1.AbortResponse\x12R\n" +
	"\vWatchEvents\x12\x1f.q15.chat.v1.WatchEventsRequest\x1a .q15.chat.v1.WatchEventsResponse0\x01\x12J\n" +
	"\tListTurns\x12\x1d.q15.chat.v1.ListTurnsRequest\x1a\x1e.q15.chat.v1.ListTurnsResponse\x12F\n" +
	"\aDeliver\x12\x1b.q15.chat.v1.DeliverRequest\x1a\x1c.q15.chat.v1.DeliverResponse0\x01B7Z5github.com/q15co/q15/libs/chat-contract/chatpb;chatpbb\x06proto3"

var (
	file_q15_chat_v1_chat_proto_rawDescOnce sync.Once
	file_q15_chat_v1_chat_proto_rawDescData []byte
)

func file_q15_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_q15_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_q15_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_q15_chat_v1_chat_proto_rawDesc), len(file_q15_chat_v1_chat_proto_rawDesc)))
	})
	return file_q15_chat_v1_chat_proto_rawDescData
}

var file_q15_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_q15_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_q15_chat_v1_chat_proto_goTypes = []any{
	(SessionState)(0),              // 0: q15.chat.v1.SessionState
	(RunStatus)(0),                 // 1: q15.chat.v1.RunStatus
	(*GetRuntimeInfoRequest)(nil),  // 2: q15.chat.v1.GetRuntimeInfoRequest
	(*RuntimeCapability)(nil),      // 3: q15.chat.v1.RuntimeCapability
	(*GetRuntimeInfoResponse)(nil), // 4: q15.chat.v1.GetRuntimeInfoResponse
	(*Session)(nil),                // 5: q15.chat.v1.Session
	(*OpenSessionRequest)(nil),     // 6: q15.chat.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),    // 7: q15.chat.v1.OpenSessionResponse
	(*SendMessageRequest)(nil),     // 8: q15.chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),    // 9: q15.chat.v1.SendMessageResponse
	(*AbortRequest)(nil),           // 10: q15.chat.v1.AbortRequest
	(*AbortResponse)(nil),          // 11: q15.chat.v1.AbortResponse
	(*WatchEventsRequest)(nil),     // 12: q15.chat.v1.WatchEventsRequest
	(*WatchEventsResponse)(nil),    // 13: q15.chat.v1.WatchEventsResponse
	(*SessionEvent)(nil),           // 14: q15.chat.v1.SessionEvent
	(*SessionOpened)(nil),          // 15: q15.chat.v1.SessionOpened
	(*RunStarted)(nil),             // 16: q15.chat.v1.RunStarted
	(*ModelTurnStarted)(nil),       // 17: q15.chat.v1.ModelTurnStarted
	(*ModelTurnDelta)(nil),         // 18: q15.chat.v1.ModelTurnDelta
	(*ModelReasoningDelta)(nil),    // 19: q15.chat.v1.ModelReasoningDelta
	(*ToolCall)(nil),               // 20: q15.chat.v1.ToolCall
	(*ToolStarted)(nil),            // 21: q15.chat.v1.ToolStarted
	(*ToolFinished)(nil),           // 22: q15.chat.v1.ToolFinished
	(*RunFinished)(nil),            // 23: q15.chat.v1.RunFinished
	(*RunFailed)(nil),              // 24: q15.chat.v1.RunFailed
	(*Snapshot)(nil),               // 25: q15.chat.v1.Snapshot
	(*Notice)(nil),                 // 26: q15.chat.v1.Notice
	(*ListTurnsRequest)(nil),       // 27: q15.chat.v1.ListTurnsRequest
	(*ListTurnsResponse)(nil),      // 28: q15.chat.v1.ListTurnsResponse
	(*Turn)(nil),                   // 29: q15.chat.v1.Turn
	(*Message)(nil),                // 30: q15.chat.v1.Message
	(*MessagePart)(nil),            // 31: q15.chat.v1.MessagePart
	(*DeliverRequest)(nil),         // 32: q15.chat.v1.DeliverRequest
	(*DeliverResponse)(nil),        // 33: q15.chat.v1.DeliverResponse
	(*BrowserPacket)(nil),          // 34: q15.chat.v1.BrowserPacket
	(*BrowserHistoryRequest)(nil),  // 35: q15.chat.v1.BrowserHistoryRequest
	(*timestamppb.Timestamp)(nil),  // 36: google.protobuf.Timestamp
}
var file_q15_chat_v1_chat_proto_depIdxs = []int32{
	3,  // 0: q15.chat.v1.GetRuntimeInfoResponse.capabilities:type_name -> q15.chat.v1.RuntimeCapability
	0,  // 1: q15.chat.v1.Session.state:type_name -> q15.chat.v1.SessionState
	36, // 2: q15.chat.v1.Session.opened_at:type_name -> google.protobuf.Timestamp
	5,  // 3: q15.chat.v1.OpenSessionResponse.session:type_name -> q15.chat.v1.Session
	5,  // 4: q15.chat.v1.SendMessageResponse.session:type_name -> q15.chat.v1.Session
	5,  // 5: q15.chat.v1.AbortResponse.session:type_name -> q15.chat.v1.Session
	14, // 6: q15.chat.v1.WatchEventsResponse.event:type_name -> q15.chat.v1.SessionEvent
	36, // 7: q15.chat.v1.SessionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	15, // 8: q15.chat.v1.SessionEvent.session_opened:type_name -> q15.chat.v1.SessionOpened
	16, // 9: q15.chat.v1.SessionEvent.run_started:type_name -> q15.chat.v1.RunStarted
	17, // 10: q15.chat.v1.SessionEvent.model_turn_started:type_name -> q15.chat.v1.ModelTurnStarted
	18, // 11: q15.chat.v1.SessionEvent.model_turn_delta:type_name -> q15.chat.v1.ModelTurnDelta
	19, // 12: q15.chat.v1.SessionEvent.model_reasoning_delta:type_name -> q15.chat.v1.ModelReasoningDelta
	21, // 13: q15.chat.v1.SessionEvent.tool_started:type_name -> q15.chat.v1.ToolStarted
	22, // 14: q15.chat.v1.SessionEvent.tool_finished:type_name -> q15.chat.v1.ToolFinished
	23, // 15: q15.chat.v1.SessionEvent.run_finished:type_name -> q15.chat.v1.RunFinished
	24, // 16: q15.chat.v1.SessionEvent.run_failed:type_name -> q15.chat.v1.RunFailed
	25, // 17: q15.chat.v1.SessionEvent.snapshot:type_name -> q15.chat.v1.Snapshot
	26, // 18: q15.chat.v1.SessionEvent.notice:type_name -> q15.chat.v1.Notice
	20, // 19: q15.chat.v1.ToolStarted.call:type_name -> q15.chat.v1.ToolCall
	20, // 20: q15.chat.v1.ToolFinished.call:type_name -> q15.chat.v1.ToolCall
	1,  // 21: q15.chat.v1.RunFinished.status:type_name -> q15.chat.v1.RunStatus
	1,  // 22: q15.chat.v1.RunFailed.status:type_name -> q15.chat.v1.RunStatus
	29, // 23: q15.chat.v1.ListTurnsResponse.turns:type_name -> q15.chat.v1.Turn
	36, // 24: q15.chat.v1.Turn.created_at:type_name -> google.protobuf.Timestamp
	30, // 25: q15.chat.v1.Turn.messages:type_name -> q15.chat.v1.Message
	31, // 26: q15.chat.v1.Message.parts:type_name -> q15.chat.v1.MessagePart
	20, // 27: q15.chat.v1.MessagePart.tool_call:type_name -> q15.chat.v1.ToolCall
	36, // 28: q15.chat.v1.DeliverResponse.queued_at:type_name -> google.protobuf.Timestamp
	34, // 29: q15.chat.v1.ChatService.BrowserChannel:input_type -> q15.chat.v1.BrowserPacket
	35, // 30: q15.chat.v1.ChatService.BrowserHistory:input_type -> q15.chat.v1.BrowserHistoryRequest
	2,  // 31: q15.chat.v1.ChatService.GetRuntimeInfo:input_type -> q15.chat.v1.GetRuntimeInfoRequest
	6,  // 32: q15.chat.v1.ChatService.OpenSession:input_type -> q15.chat.v1.OpenSessionRequest
	8,  // 33: q15.chat.v1.ChatService.SendMessage:input_type -> q15.chat.v1.SendMessageRequest
	10, // 34: q15.chat.v1.ChatService.Abort:input_type -> q15.chat.v1.AbortRequest
	12, // 35: q15.chat.v1.ChatService.WatchEvents:input_type -> q15.chat.v1.WatchEventsRequest
	27, // 36: q15.chat.v1.ChatService.ListTurns:input_type -> q15.chat.v1.ListTurnsRequest
	32, // 37: q15.chat.v1.ChatService.Deliver:input_type -> q15.chat.v1.DeliverRequest
	34, // 38: q15.chat.v1.ChatService.BrowserChannel:output_type -> q15.chat.v1.BrowserPacket
	34, // 39: q15.chat.v1.ChatService.BrowserHistory:output_type -> q15.chat.v1.BrowserPacket
	4,  // 40: q15.chat.v1.ChatService.GetRuntimeInfo:output_type -> q15.chat.v1.GetRuntimeInfoResponse
	7,  // 41: q15.chat.v1.ChatService.OpenSession:output_type -> q15.chat.v1.OpenSessionResponse
	9,  // 42: q15.chat.v1.ChatService.SendMessage:output_type -> q15.chat.v1.SendMessageResponse
	11, // 43: q15.chat.v1.ChatService.Abort:output_type -> q15.chat.v1.AbortResponse
	13, // 44: q15.chat.v1.ChatService.WatchEvents:output_type -> q15.chat.v1.WatchEventsResponse
	28, // 45: q15.chat.v1.ChatService.ListTurns:output_type -> q15.chat.v1.ListTurnsResponse
	33, // 46: q15.chat.v1.ChatService.Deliver:output_type -> q15.chat.v1.DeliverResponse
	38, // [38:47] is the sub-list for method output_type
	29, // [29:38] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_q15_chat_v1_chat_proto_init() }
func file_q15_chat_v1_chat_proto_init() {
	if File_q15_chat_v1_chat_proto != nil {
		return
	}
	file_q15_chat_v1_chat_proto_msgTypes[12].OneofWrappers = []any{
		(*SessionEvent_SessionOpened)(nil),
		(*SessionEvent_RunStarted)(nil),
		(*SessionEvent_ModelTurnStarted)(nil),
		(*SessionEvent_ModelTurnDelta)(nil),
		(*SessionEvent_ModelReasoningDelta)(nil),
		(*SessionEvent_ToolStarted)(nil),
		(*SessionEvent_ToolFinished)(nil),
		(*SessionEvent_RunFinished)(nil),
		(*SessionEvent_RunFailed)(nil),
		(*SessionEvent_Snapshot)(nil),
		(*SessionEvent_Notice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_q15_chat_v1_chat_proto_rawDesc), len(file_q15_chat_v1_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_q15_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_q15_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_q15_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_q15_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_q15_chat_v1_chat_proto = out.File
	file_q15_chat_v1_chat_proto_goTypes = nil
	file_q15_chat_v1_chat_proto_depIdxs = nil
}
