// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: q15/chat/v1/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_GetRuntimeInfo_FullMethodName = "/q15.chat.v1.ChatService/GetRuntimeInfo"
	ChatService_OpenSession_FullMethodName    = "/q15.chat.v1.ChatService/OpenSession"
	ChatService_SendMessage_FullMethodName    = "/q15.chat.v1.ChatService/SendMessage"
	ChatService_Abort_FullMethodName          = "/q15.chat.v1.ChatService/Abort"
	ChatService_WatchEvents_FullMethodName    = "/q15.chat.v1.ChatService/WatchEvents"
	ChatService_ListTurns_FullMethodName      = "/q15.chat.v1.ChatService/ListTurns"
	ChatService_Deliver_FullMethodName        = "/q15.chat.v1.ChatService/Deliver"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatService is the agent-side conversation surface consumed by q15-web.
//
// The direction is the opposite of q15.exec.v1.ExecutionService: there the
// agent is the client and the sandbox helper is the server, here the agent is
// the server, because the conversation lives in the agent's transcript and the
// agent owns the run event stream. q15-web dials a Unix socket, so the socket
// is the agent's only inbound surface and it carries no credential.
//
// Compatibility rule, which is the reason this is a contract rather than a
// hand-rolled codec: the wire format is additive-only. Add fields with new
// numbers, never renumber or reuse one, and reserve both the number and the
// name of anything removed. ProtocolVersion is bumped only for a breaking
// change, and q15-web treats a mismatch as a hard startup failure.
//
// This contract versions q15-web against the agent. It does not version the
// browser: the browser never speaks gRPC, and its contract is the WebSocket
// envelope plus the frozen frame fixtures, not this handshake.
type ChatServiceClient interface {
	// GetRuntimeInfo is the startup handshake: protocol version, transcript head
	// sequence and enabled capabilities.
	GetRuntimeInfo(ctx context.Context, in *GetRuntimeInfoRequest, opts ...grpc.CallOption) (*GetRuntimeInfoResponse, error)
	// OpenSession allocates a conversation session. One session owns at most one
	// in-flight run; extra sends queue rather than starting a second run.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	// SendMessage delivers one user message and starts a run when the session is
	// idle.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Abort cancels the in-flight run of a session.
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	// WatchEvents streams run progress. after_event_index resumes a dropped
	// stream, mirroring WatchSessionRequest in the exec contract.
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEventsResponse], error)
	// ListTurns pages the durable transcript. Read-only.
	ListTurns(ctx context.Context, in *ListTurnsRequest, opts ...grpc.CallOption) (*ListTurnsResponse, error)
	// Deliver opens the outbound subscription. Because the agent is the server,
	// a subscription the client holds open is the only way it can push
	// unsolicited messages out, so this method maps the agent's outbound endpoint
	// direction onto a stream: every bus.OutboundMessage bound for this channel is
	// fanned out to every open stream. Slice 1 carries text only, because
	// bus.OutboundMessage carries no parts.
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliverResponse], error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) GetRuntimeInfo(ctx context.Context, in *GetRuntimeInfoRequest, opts ...grpc.CallOption) (*GetRuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeInfoResponse)
	err := c.cc.Invoke(ctx, ChatService_GetRuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, ChatService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, ChatService_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, WatchEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_WatchEventsClient = grpc.ServerStreamingClient[WatchEventsResponse]

func (c *chatServiceClient) ListTurns(ctx context.Context, in *ListTurnsRequest, opts ...grpc.CallOption) (*ListTurnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTurnsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliverResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], ChatService_Deliver_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeliverRequest, DeliverResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_DeliverClient = grpc.ServerStreamingClient[DeliverResponse]

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ChatService is the agent-side conversation surface consumed by q15-web.
//
// The direction is the opposite of q15.exec.v1.ExecutionService: there the
// agent is the client and the sandbox helper is the server, here the agent is
// the server, because the conversation lives in the agent's transcript and the
// agent owns the run event stream. q15-web dials a Unix socket, so the socket
// is the agent's only inbound surface and it carries no credential.
//
// Compatibility rule, which is the reason this is a contract rather than a
// hand-rolled codec: the wire format is additive-only. Add fields with new
// numbers, never renumber or reuse one, and reserve both the number and the
// name of anything removed. ProtocolVersion is bumped only for a breaking
// change, and q15-web treats a mismatch as a hard startup failure.
//
// This contract versions q15-web against the agent. It does not version the
// browser: the browser never speaks gRPC, and its contract is the WebSocket
// envelope plus the frozen frame fixtures, not this handshake.
type ChatServiceServer interface {
	// GetRuntimeInfo is the startup handshake: protocol version, transcript head
	// sequence and enabled capabilities.
	GetRuntimeInfo(context.Context, *GetRuntimeInfoRequest) (*GetRuntimeInfoResponse, error)
	// OpenSession allocates a conversation session. One session owns at most one
	// in-flight run; extra sends queue rather than starting a second run.
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	// SendMessage delivers one user message and starts a run when the session is
	// idle.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Abort cancels the in-flight run of a session.
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	// WatchEvents streams run progress. after_event_index resumes a dropped
	// stream, mirroring WatchSessionRequest in the exec contract.
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[WatchEventsResponse]) error
	// ListTurns pages the durable transcript. Read-only.
	ListTurns(context.Context, *ListTurnsRequest) (*ListTurnsResponse, error)
	// Deliver opens the outbound subscription. Because the agent is the server,
	// a subscription the client holds open is the only way it can push
	// unsolicited messages out, so this method maps the agent's outbound endpoint
	// direction onto a stream: every bus.OutboundMessage bound for this channel is
	// fanned out to every open stream. Slice 1 carries text only, because
	// bus.OutboundMessage carries no parts.
	Deliver(*DeliverRequest, grpc.ServerStreamingServer[DeliverResponse]) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) GetRuntimeInfo(context.Context, *GetRuntimeInfoRequest) (*GetRuntimeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeInfo not implemented")
}
func (UnimplementedChatServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedChatServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedChatServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[WatchEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedChatServiceServer) ListTurns(context.Context, *ListTurnsRequest) (*ListTurnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTurns not implemented")
}
func (UnimplementedChatServiceServer) Deliver(*DeliverRequest, grpc.ServerStreamingServer[DeliverResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_GetRuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetRuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetRuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetRuntimeInfo(ctx, req.(*GetRuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, WatchEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_WatchEventsServer = grpc.ServerStreamingServer[WatchEventsResponse]

func _ChatService_ListTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListTurns(ctx, req.(*ListTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Deliver_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeliverRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Deliver(m, &grpc.GenericServerStream[DeliverRequest, DeliverResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_DeliverServer = grpc.ServerStreamingServer[DeliverResponse]

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "q15.chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuntimeInfo",
			Handler:    _ChatService_GetRuntimeInfo_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _ChatService_OpenSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _ChatService_Abort_Handler,
		},
		{
			MethodName: "ListTurns",
			Handler:    _ChatService_ListTurns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _ChatService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Deliver",
			Handler:       _ChatService_Deliver_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "q15/chat/v1/chat.proto",
}
