// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: q15/exec/v1/execution.proto

package execpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_STARTING    SessionState = 1
	SessionState_SESSION_STATE_RUNNING     SessionState = 2
	SessionState_SESSION_STATE_EXITED      SessionState = 3
	SessionState_SESSION_STATE_TERMINATING SessionState = 4
	SessionState_SESSION_STATE_TERMINATED  SessionState = 5
	SessionState_SESSION_STATE_FAILED      SessionState = 6
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_STARTING",
		2: "SESSION_STATE_RUNNING",
		3: "SESSION_STATE_EXITED",
		4: "SESSION_STATE_TERMINATING",
		5: "SESSION_STATE_TERMINATED",
		6: "SESSION_STATE_FAILED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_STARTING":    1,
		"SESSION_STATE_RUNNING":     2,
		"SESSION_STATE_EXITED":      3,
		"SESSION_STATE_TERMINATING": 4,
		"SESSION_STATE_TERMINATED":  5,
		"SESSION_STATE_FAILED":      6,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_q15_exec_v1_execution_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_q15_exec_v1_execution_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{0}
}

type GetRuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeInfoRequest) Reset() {
	*x = GetRuntimeInfoRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoRequest) ProtoMessage() {}

func (x *GetRuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{0}
}

type RuntimeCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeCapability) Reset() {
	*x = RuntimeCapability{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCapability) ProtoMessage() {}

func (x *RuntimeCapability) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCapability.ProtoReflect.Descriptor instead.
func (*RuntimeCapability) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeCapability) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetRuntimeInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceVersion      string                 `protobuf:"bytes,1,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	ExecutorType        string                 `protobuf:"bytes,2,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`
	WorkspaceDir        string                 `protobuf:"bytes,3,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	MemoryDir           string                 `protobuf:"bytes,4,opt,name=memory_dir,json=memoryDir,proto3" json:"memory_dir,omitempty"`
	SkillsDir           string                 `protobuf:"bytes,5,opt,name=skills_dir,json=skillsDir,proto3" json:"skills_dir,omitempty"`
	Capabilities        []*RuntimeCapability   `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProxyEnabled        bool                   `protobuf:"varint,7,opt,name=proxy_enabled,json=proxyEnabled,proto3" json:"proxy_enabled,omitempty"`
	ProxyPolicyRevision string                 `protobuf:"bytes,8,opt,name=proxy_policy_revision,json=proxyPolicyRevision,proto3" json:"proxy_policy_revision,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRuntimeInfoResponse) Reset() {
	*x = GetRuntimeInfoResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeInfoResponse) ProtoMessage() {}

func (x *GetRuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuntimeInfoResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetMemoryDir() string {
	if x != nil {
		return x.MemoryDir
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetSkillsDir() string {
	if x != nil {
		return x.SkillsDir
	}
	return ""
}

func (x *GetRuntimeInfoResponse) GetCapabilities() []*RuntimeCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetRuntimeInfoResponse) GetProxyEnabled() bool {
	if x != nil {
		return x.ProxyEnabled
	}
	return false
}

func (x *GetRuntimeInfoResponse) GetProxyPolicyRevision() string {
	if x != nil {
		return x.ProxyPolicyRevision
	}
	return ""
}

type Session struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command           string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Packages          []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	WorkingDir        string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	StdinOpen         bool                   `protobuf:"varint,5,opt,name=stdin_open,json=stdinOpen,proto3" json:"stdin_open,omitempty"`
	State             SessionState           `protobuf:"varint,6,opt,name=state,proto3,enum=q15.exec.v1.SessionState" json:"state,omitempty"`
	NextEventIndex    int64                  `protobuf:"varint,7,opt,name=next_event_index,json=nextEventIndex,proto3" json:"next_event_index,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode          int32                  `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode       bool                   `protobuf:"varint,11,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	TerminationReason string                 `protobuf:"bytes,12,opt,name=termination_reason,json=terminationReason,proto3" json:"termination_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Session) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *Session) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Session) GetStdinOpen() bool {
	if x != nil {
		return x.StdinOpen
	}
	return false
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetNextEventIndex() int64 {
	if x != nil {
		return x.NextEventIndex
	}
	return 0
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Session) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Session) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *Session) GetTerminationReason() string {
	if x != nil {
		return x.TerminationReason
	}
	return ""
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Packages      []string               `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	KeepStdinOpen bool                   `protobuf:"varint,4,opt,name=keep_stdin_open,json=keepStdinOpen,proto3" json:"keep_stdin_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *StartSessionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartSessionRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *StartSessionRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StartSessionRequest) GetKeepStdinOpen() bool {
	if x != nil {
		return x.KeepStdinOpen
	}
	return false
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *StartSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type WatchSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterEventIndex int64                  `protobuf:"varint,2,opt,name=after_event_index,json=afterEventIndex,proto3" json:"after_event_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchSessionRequest) Reset() {
	*x = WatchSessionRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionRequest) ProtoMessage() {}

func (x *WatchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{8}
}

func (x *WatchSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchSessionRequest) GetAfterEventIndex() int64 {
	if x != nil {
		return x.AfterEventIndex
	}
	return 0
}

type WatchSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *SessionEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionResponse) Reset() {
	*x = WatchSessionResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionResponse) ProtoMessage() {}

func (x *WatchSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionResponse.ProtoReflect.Descriptor instead.
func (*WatchSessionResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{9}
}

func (x *WatchSessionResponse) GetEvent() *SessionEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WriteSessionStdinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CloseStdin    bool                   `protobuf:"varint,3,opt,name=close_stdin,json=closeStdin,proto3" json:"close_stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSessionStdinRequest) Reset() {
	*x = WriteSessionStdinRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSessionStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSessionStdinRequest) ProtoMessage() {}

func (x *WriteSessionStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSessionStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteSessionStdinRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{10}
}

func (x *WriteSessionStdinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteSessionStdinRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteSessionStdinRequest) GetCloseStdin() bool {
	if x != nil {
		return x.CloseStdin
	}
	return false
}

type WriteSessionStdinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSessionStdinResponse) Reset() {
	*x = WriteSessionStdinResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSessionStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSessionStdinResponse) ProtoMessage() {}

func (x *WriteSessionStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSessionStdinResponse.ProtoReflect.Descriptor instead.
func (*WriteSessionStdinResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{11}
}

func (x *WriteSessionStdinResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *WriteSessionStdinResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{12}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateSessionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TerminateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionResponse) Reset() {
	*x = TerminateSessionResponse{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionResponse) ProtoMessage() {}

func (x *TerminateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminateSessionResponse) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{13}
}

func (x *TerminateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SessionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventIndex int64                  `protobuf:"varint,1,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SessionEvent_Started
	//	*SessionEvent_Stdout
	//	*SessionEvent_Stderr
	//	*SessionEvent_StdinClosed
	//	*SessionEvent_Exited
	//	*SessionEvent_Terminated
	Event         isSessionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{14}
}

func (x *SessionEvent) GetEventIndex() int64 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *SessionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SessionEvent) GetEvent() isSessionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SessionEvent) GetStarted() *SessionStarted {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *SessionEvent) GetStdout() *SessionOutput {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *SessionEvent) GetStderr() *SessionOutput {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *SessionEvent) GetStdinClosed() *SessionStdinClosed {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_StdinClosed); ok {
			return x.StdinClosed
		}
	}
	return nil
}

func (x *SessionEvent) GetExited() *SessionExited {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *SessionEvent) GetTerminated() *SessionTerminated {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Terminated); ok {
			return x.Terminated
		}
	}
	return nil
}

type isSessionEvent_Event interface {
	isSessionEvent_Event()
}

type SessionEvent_Started struct {
	Started *SessionStarted `protobuf:"bytes,3,opt,name=started,proto3,oneof"`
}

type SessionEvent_Stdout struct {
	Stdout *SessionOutput `protobuf:"bytes,4,opt,name=stdout,proto3,oneof"`
}

type SessionEvent_Stderr struct {
	Stderr *SessionOutput `protobuf:"bytes,5,opt,name=stderr,proto3,oneof"`
}

type SessionEvent_StdinClosed struct {
	StdinClosed *SessionStdinClosed `protobuf:"bytes,6,opt,name=stdin_closed,json=stdinClosed,proto3,oneof"`
}

type SessionEvent_Exited struct {
	Exited *SessionExited `protobuf:"bytes,7,opt,name=exited,proto3,oneof"`
}

type SessionEvent_Terminated struct {
	Terminated *SessionTerminated `protobuf:"bytes,8,opt,name=terminated,proto3,oneof"`
}

func (*SessionEvent_Started) isSessionEvent_Event() {}

func (*SessionEvent_Stdout) isSessionEvent_Event() {}

func (*SessionEvent_Stderr) isSessionEvent_Event() {}

func (*SessionEvent_StdinClosed) isSessionEvent_Event() {}

func (*SessionEvent_Exited) isSessionEvent_Event() {}

func (*SessionEvent_Terminated) isSessionEvent_Event() {}

type SessionStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStarted) Reset() {
	*x = SessionStarted{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStarted) ProtoMessage() {}

func (x *SessionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStarted.ProtoReflect.Descriptor instead.
func (*SessionStarted) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{15}
}

func (x *SessionStarted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOutput) Reset() {
	*x = SessionOutput{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOutput) ProtoMessage() {}

func (x *SessionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOutput.ProtoReflect.Descriptor instead.
func (*SessionOutput) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{16}
}

func (x *SessionOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SessionStdinClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStdinClosed) Reset() {
	*x = SessionStdinClosed{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStdinClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStdinClosed) ProtoMessage() {}

func (x *SessionStdinClosed) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStdinClosed.ProtoReflect.Descriptor instead.
func (*SessionStdinClosed) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{17}
}

type SessionExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExited) Reset() {
	*x = SessionExited{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExited) ProtoMessage() {}

func (x *SessionExited) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExited.ProtoReflect.Descriptor instead.
func (*SessionExited) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{18}
}

func (x *SessionExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type SessionTerminated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTerminated) Reset() {
	*x = SessionTerminated{}
	mi := &file_q15_exec_v1_execution_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTerminated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTerminated) ProtoMessage() {}

func (x *SessionTerminated) ProtoReflect() protoreflect.Message {
	mi := &file_q15_exec_v1_execution_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTerminated.ProtoReflect.Descriptor instead.
func (*SessionTerminated) Descriptor() ([]byte, []int) {
	return file_q15_exec_v1_execution_proto_rawDescGZIP(), []int{19}
}

func (x *SessionTerminated) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SessionTerminated) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

var File_q15_exec_v1_execution_proto protoreflect.FileDescriptor

const file_q15_exec_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x1bq15/exec/v1/execution.proto\x12\vq15.exec.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetRuntimeInfoRequest\"A\n" +
	"\x11RuntimeCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xe6\x02\n" +
	"\x16GetRuntimeInfoResponse\x12'\n" +
	"\x0fservice_version\x18\x01 \x01(\tR\x0eserviceVersion\x12#\n" +
	"\rexecutor_type\x18\x02 \x01(\tR\fexecutorType\x12#\n" +
	"\rworkspace_dir\x18\x03 \x01(\tR\fworkspaceDir\x12\x1d\n" +
	"\n" +
	"memory_dir\x18\x04 \x01(\tR\tmemoryDir\x12\x1d\n" +
	"\n" +
	"skills_dir\x18\x05 \x01(\tR\tskillsDir\x12B\n" +
	"\fcapabilities\x18\x06 \x03(\v2\x1e.q15.exec.v1.RuntimeCapabilityR\fcapabilities\x12#\n" +
	"\rproxy_enabled\x18\a \x01(\bR\fproxyEnabled\x122\n" +
	"\x15proxy_policy_revision\x18\b \x01(\tR\x13proxyPolicyRevision\"\xe1\x03\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x1d\n" +
	"\n" +
	"stdin_open\x18\x05 \x01(\bR\tstdinOpen\x12/\n" +
	"\x05state\x18\x06 \x01(\x0e2\x19.q15.exec.v1.SessionStateR\x05state\x12(\n" +
	"\x10next_event_index\x18\a \x01(\x03R\x0enextEventIndex\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\n" +
	" \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\v \x01(\bR\vhasExitCode\x12-\n" +
	"\x12termination_reason\x18\f \x01(\tR\x11terminationReason\"\x94\x01\n" +
	"\x13StartSessionRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12&\n" +
	"\x0fkeep_stdin_open\x18\x04 \x01(\bR\rkeepStdinOpen\"F\n" +
	"\x14StartSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.exec.v1.SessionR\asession\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"D\n" +
	"\x12GetSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.exec.v1.SessionR\asession\"`\n" +
	"\x13WatchSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11after_event_index\x18\x02 \x01(\x03R\x0fafterEventIndex\"G\n" +
	"\x14WatchSessionResponse\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.q15.exec.v1.SessionEventR\x05event\"n\n" +
	"\x18WriteSessionStdinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vclose_stdin\x18\x03 \x01(\bR\n" +
	"closeStdin\"p\n" +
	"\x19WriteSessionStdinResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.exec.v1.SessionR\asession\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\"N\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"J\n" +
	"\x18TerminateSessionResponse\x12.\n" +
	"\asession\x18\x01 \x01(\v2\x14.q15.exec.v1.SessionR\asession\"\xd8\x03\n" +
	"\fSessionEvent\x12\x1f\n" +
	"\vevent_index\x18\x01 \x01(\x03R\n" +
	"eventIndex\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x127\n" +
	"\astarted\x18\x03 \x01(\v2\x1b.q15.exec.v1.SessionStartedH\x00R\astarted\x124\n" +
	"\x06stdout\x18\x04 \x01(\v2\x1a.q15.exec.v1.SessionOutputH\x00R\x06stdout\x124\n" +
	"\x06stderr\x18\x05 \x01(\v2\x1a.q15.exec.v1.SessionOutputH\x00R\x06stderr\x12D\n" +
	"\fstdin_closed\x18\x06 \x01(\v2\x1f.q15.exec.v1.SessionStdinClosedH\x00R\vstdinClosed\x124\n" +
	"\x06exited\x18\a \x01(\v2\x1a.q15.exec.v1.SessionExitedH\x00R\x06exited\x12@\n" +
	"\n" +
	"terminated\x18\b \x01(\v2\x1e.q15.exec.v1.SessionTerminatedH\x00R\n" +
	"terminatedB\a\n" +
	"\x05event\"/\n" +
	"\x0eSessionStarted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"#\n" +
	"\rSessionOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x14\n" +
	"\x12SessionStdinClosed\",\n" +
	"\rSessionExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"A\n" +
	"\x11SessionTerminated\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force*\xd5\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATE_EXITED\x10\x03\x12\x1d\n" +
	"\x19SESSION_STATE_TERMINATING\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATE_TERMINATED\x10\x05\x12\x18\n" +
	"\x14SESSION_STATE_FAILED\x10\x062\xad\x04\n" +
	"\x10ExecutionService\x12Y\n" +
	"\x0eGetRuntimeInfo\x12\".q15.exec.v1.GetRuntimeInfoRequest\x1a#.q15.exec.v1.GetRuntimeInfoResponse\x12S\n" +
	"\fStartSession\x12 .q15.exec.v1.StartSessionRequest\x1a!.q15.exec.v1.StartSessionResponse\x12M\n" +
	"\n" +
	"GetSession\x12\x1e.q15.exec.v1.GetSessionRequest\x1a\x1f.q15.exec.v1.GetSessionResponse\x12U\n" +
	"\fWatchSession\x12 .q15.exec.v1.WatchSessionRequest\x1a!.q15.exec.v1.WatchSessionResponse0\x01\x12b\n" +
	"\x11WriteSessionStdin\x12%.q15.exec.v1.WriteSessionStdinRequest\x1a&.q15.exec.v1.WriteSessionStdinResponse\x12_\n" +
	"\x10TerminateSession\x12$.q15.exec.v1.TerminateSessionRequest\x1a%.q15.exec.v1.TerminateSessionResponseB7Z5github.com/q15co/q15/libs/exec-contract/execpb;execpbb\x06proto3"

var (
	file_q15_exec_v1_execution_proto_rawDescOnce sync.Once
	file_q15_exec_v1_execution_proto_rawDescData []byte
)

func file_q15_exec_v1_execution_proto_rawDescGZIP() []byte {
	file_q15_exec_v1_execution_proto_rawDescOnce.Do(func() {
		file_q15_exec_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_q15_exec_v1_execution_proto_rawDesc), len(file_q15_exec_v1_execution_proto_rawDesc)))
	})
	return file_q15_exec_v1_execution_proto_rawDescData
}

var file_q15_exec_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_q15_exec_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_q15_exec_v1_execution_proto_goTypes = []any{
	(SessionState)(0),                 // 0: q15.exec.v1.SessionState
	(*GetRuntimeInfoRequest)(nil),     // 1: q15.exec.v1.GetRuntimeInfoRequest
	(*RuntimeCapability)(nil),         // 2: q15.exec.v1.RuntimeCapability
	(*GetRuntimeInfoResponse)(nil),    // 3: q15.exec.v1.GetRuntimeInfoResponse
	(*Session)(nil),                   // 4: q15.exec.v1.Session
	(*StartSessionRequest)(nil),       // 5: q15.exec.v1.StartSessionRequest
	(*StartSessionResponse)(nil),      // 6: q15.exec.v1.StartSessionResponse
	(*GetSessionRequest)(nil),         // 7: q15.exec.v1.GetSessionRequest
	(*GetSessionResponse)(nil),        // 8: q15.exec.v1.GetSessionResponse
	(*WatchSessionRequest)(nil),       // 9: q15.exec.v1.WatchSessionRequest
	(*WatchSessionResponse)(nil),      // 10: q15.exec.v1.WatchSessionResponse
	(*WriteSessionStdinRequest)(nil),  // 11: q15.exec.v1.WriteSessionStdinRequest
	(*WriteSessionStdinResponse)(nil), // 12: q15.exec.v1.WriteSessionStdinResponse
	(*TerminateSessionRequest)(nil),   // 13: q15.exec.v1.TerminateSessionRequest
	(*TerminateSessionResponse)(nil),  // 14: q15.exec.v1.TerminateSessionResponse
	(*SessionEvent)(nil),              // 15: q15.exec.v1.SessionEvent
	(*SessionStarted)(nil),            // 16: q15.exec.v1.SessionStarted
	(*SessionOutput)(nil),             // 17: q15.exec.v1.SessionOutput
	(*SessionStdinClosed)(nil),        // 18: q15.exec.v1.SessionStdinClosed
	(*SessionExited)(nil),             // 19: q15.exec.v1.SessionExited
	(*SessionTerminated)(nil),         // 20: q15.exec.v1.SessionTerminated
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_q15_exec_v1_execution_proto_depIdxs = []int32{
	2,  // 0: q15.exec.v1.GetRuntimeInfoResponse.capabilities:type_name -> q15.exec.v1.RuntimeCapability
	0,  // 1: q15.exec.v1.Session.state:type_name -> q15.exec.v1.SessionState
	21, // 2: q15.exec.v1.Session.started_at:type_name -> google.protobuf.Timestamp
	21, // 3: q15.exec.v1.Session.finished_at:type_name -> google.protobuf.Timestamp
	4,  // 4: q15.exec.v1.StartSessionResponse.session:type_name -> q15.exec.v1.Session
	4,  // 5: q15.exec.v1.GetSessionResponse.session:type_name -> q15.exec.v1.Session
	15, // 6: q15.exec.v1.WatchSessionResponse.event:type_name -> q15.exec.v1.SessionEvent
	4,  // 7: q15.exec.v1.WriteSessionStdinResponse.session:type_name -> q15.exec.v1.Session
	4,  // 8: q15.exec.v1.TerminateSessionResponse.session:type_name -> q15.exec.v1.Session
	21, // 9: q15.exec.v1.SessionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	16, // 10: q15.exec.v1.SessionEvent.started:type_name -> q15.exec.v1.SessionStarted
	17, // 11: q15.exec.v1.SessionEvent.stdout:type_name -> q15.exec.v1.SessionOutput
	17, // 12: q15.exec.v1.SessionEvent.stderr:type_name -> q15.exec.v1.SessionOutput
	18, // 13: q15.exec.v1.SessionEvent.stdin_closed:type_name -> q15.exec.v1.SessionStdinClosed
	19, // 14: q15.exec.v1.SessionEvent.exited:type_name -> q15.exec.v1.SessionExited
	20, // 15: q15.exec.v1.SessionEvent.terminated:type_name -> q15.exec.v1.SessionTerminated
	1,  // 16: q15.exec.v1.ExecutionService.GetRuntimeInfo:input_type -> q15.exec.v1.GetRuntimeInfoRequest
	5,  // 17: q15.exec.v1.ExecutionService.StartSession:input_type -> q15.exec.v1.StartSessionRequest
	7,  // 18: q15.exec.v1.ExecutionService.GetSession:input_type -> q15.exec.v1.GetSessionRequest
	9,  // 19: q15.exec.v1.ExecutionService.WatchSession:input_type -> q15.exec.v1.WatchSessionRequest
	11, // 20: q15.exec.v1.ExecutionService.WriteSessionStdin:input_type -> q15.exec.v1.WriteSessionStdinRequest
	13, // 21: q15.exec.v1.ExecutionService.TerminateSession:input_type -> q15.exec.v1.TerminateSessionRequest
	3,  // 22: q15.exec.v1.ExecutionService.GetRuntimeInfo:output_type -> q15.exec.v1.GetRuntimeInfoResponse
	6,  // 23: q15.exec.v1.ExecutionService.StartSession:output_type -> q15.exec.v1.StartSessionResponse
	8,  // 24: q15.exec.v1.ExecutionService.GetSession:output_type -> q15.exec.v1.GetSessionResponse
	10, // 25: q15.exec.v1.ExecutionService.WatchSession:output_type -> q15.exec.v1.WatchSessionResponse
	12, // 26: q15.exec.v1.ExecutionService.WriteSessionStdin:output_type -> q15.exec.v1.WriteSessionStdinResponse
	14, // 27: q15.exec.v1.ExecutionService.TerminateSession:output_type -> q15.exec.v1.TerminateSessionResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_q15_exec_v1_execution_proto_init() }
func file_q15_exec_v1_execution_proto_init() {
	if File_q15_exec_v1_execution_proto != nil {
		return
	}
	file_q15_exec_v1_execution_proto_msgTypes[14].OneofWrappers = []any{
		(*SessionEvent_Started)(nil),
		(*SessionEvent_Stdout)(nil),
		(*SessionEvent_Stderr)(nil),
		(*SessionEvent_StdinClosed)(nil),
		(*SessionEvent_Exited)(nil),
		(*SessionEvent_Terminated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_q15_exec_v1_execution_proto_rawDesc), len(file_q15_exec_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_q15_exec_v1_execution_proto_goTypes,
		DependencyIndexes: file_q15_exec_v1_execution_proto_depIdxs,
		EnumInfos:         file_q15_exec_v1_execution_proto_enumTypes,
		MessageInfos:      file_q15_exec_v1_execution_proto_msgTypes,
	}.Build()
	File_q15_exec_v1_execution_proto = out.File
	file_q15_exec_v1_execution_proto_goTypes = nil
	file_q15_exec_v1_execution_proto_depIdxs = nil
}
