#!/usr/bin/env python3
"""Generate browser wire types directly from the Go JSON contract (no JS install)."""

import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
source = (root / "libs/chat-contract/browser/protocol/protocol.go").read_text()
source += (root / "libs/chat-contract/browser/protocol/sealed.go").read_text()
print("// Generated by scripts/generate-ui-protocol.py. Do not edit.\n")
version = re.search(r"const Version = (\d+)", source).group(1)
print(f"export const VERSION = {version} as const;\n")
scalars = {"int": "number", "uint32": "number", "int32": "number", "int64": "string", "string": "string",
           "bool": "boolean", "time.Time": "string", "json.RawMessage": "unknown"}
for i, (name, fields) in enumerate(re.findall(r"type (\w+) struct \{\n(.*?)\n\}", source, re.S)):
    if i:
        print()
    print(f"export interface {name} {{")
    for go_type, json_tag in re.findall(r'\w+\s+([\w.\[\]*]+)\s+`json:"([^"]+)"`', fields):
        field, *options = json_tag.split(",")
        optional = "?" if "omitempty" in options else ""
        array = go_type.startswith("[]")
        value_type = go_type.removeprefix("[]").removeprefix("*")
        value_type = scalars.get(value_type, value_type)
        if array:
            value_type += "[]"
        print(f"  {field}{optional}: {value_type};")
    print("}")
