#!/usr/bin/env python3
"""Generate browser wire types directly from the Go JSON contract (no JS install)."""

import ast
import json
import operator
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[1]
source = (root / "libs/chat-contract/browser/protocol/protocol.go").read_text()
source += (root / "libs/chat-contract/browser/protocol/sealed.go").read_text()
transport = (root / "libs/chat-contract/browser/protocol/transport.go").read_text()
print("// Generated by scripts/generate-ui-protocol.py. Do not edit.\n")
version = re.search(r"const Version = (\d+)", source).group(1)
print(f"export const VERSION = {version} as const;\n")
values = {}
operations = {ast.Add: operator.add, ast.Sub: operator.sub, ast.Mult: operator.mul,
              ast.Div: operator.floordiv}


def integer(expression):
    if isinstance(expression, ast.Constant) and isinstance(expression.value, int):
        return expression.value
    if isinstance(expression, ast.Name):
        return values[expression.id]
    if isinstance(expression, ast.BinOp) and type(expression.op) in operations:
        return operations[type(expression.op)](integer(expression.left), integer(expression.right))
    raise ValueError("unsupported Go transport constant")


for block in re.findall(r"const \((.*?)\n\)", transport, re.S):
    for name, expression in re.findall(r"^\s*(\w+)\s*=\s*(.+)$", block, re.M):
        value = integer(ast.parse(expression.strip(), mode="eval").body)
        values[name] = value
        print(f"export const {name} = {value} as const;")
strings = dict(re.findall(r'^\s*(\w+)\s*=\s*("[^"]*")', source, re.M))
plain = re.search(r"var plaintextFrameTypes = \[\.\.\.\]string\{(.*?)\}", transport, re.S).group(1)
plain = [json.loads(strings[name.strip()]) for name in plain.split(",") if name.strip()]
print(f"\nexport const PLAINTEXT_FRAME_TYPES = {json.dumps(plain)} as const;")
print(f"export const FRAME_TYPES = {json.dumps([json.loads(value) for value in strings.values()])} as const;\n")
scalars = {"int": "number", "uint32": "number", "int32": "number", "int64": "string", "string": "string",
           "bool": "boolean", "time.Time": "string", "json.RawMessage": "unknown"}
for i, (name, fields) in enumerate(re.findall(r"type (\w+) struct \{\n(.*?)\n\}", source, re.S)):
    if i:
        print()
    print(f"export interface {name} {{")
    for go_type, json_tag in re.findall(r'\w+\s+([\w.\[\]*]+)\s+`json:"([^"]+)"`', fields):
        field, *options = json_tag.split(",")
        optional = "?" if "omitempty" in options else ""
        array = go_type.startswith("[]")
        value_type = go_type.removeprefix("[]").removeprefix("*")
        value_type = scalars.get(value_type, value_type)
        if array:
            value_type += "[]"
        print(f"  {field}{optional}: {value_type};")
    print("}")
