#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

ensure_repo_root

hooks_dir="${REPO_ROOT}/.git/hooks"
managed_marker="q15-managed-hook"
legacy_marker="File generated by prek"

mkdir -p "${hooks_dir}"

can_replace_hook() {
	local hook_path="$1"

	[[ ! -e ${hook_path} ]] && return 0
	grep -q "${managed_marker}" "${hook_path}" && return 0
	grep -q "${legacy_marker}" "${hook_path}" && return 0
	return 1
}

pre_commit_path="${hooks_dir}/pre-commit"
pre_push_path="${hooks_dir}/pre-push"

if ! can_replace_hook "${pre_commit_path}"; then
	die "refusing to overwrite ${pre_commit_path}; remove it manually or run make hooks-uninstall first"
fi

install -m 0755 "${REPO_ROOT}/.githooks/pre-commit" "${pre_commit_path}"

if [[ -e ${pre_push_path} ]] && can_replace_hook "${pre_push_path}"; then
	rm -f "${pre_push_path}"
fi

log "installed q15 pre-commit hook"
