#!/usr/bin/env bash

TOOLS_MANIFEST_VERSION=2

SHELLCHECK_VERSION=v0.11.0
JQ_VERSION=jq-1.8.1
YQ_VERSION=v4.52.5

GOLANGCI_LINT_VERSION=v2.6.2
STATICCHECK_VERSION=2025.1.1
REVIVE_VERSION=v1.11.0
GOLINES_VERSION=v0.13.0
ACTIONLINT_VERSION=v1.7.9
SHFMT_VERSION=v3.12.0

ALEJANDRA_GIT_URL=https://github.com/kamadorueda/alejandra
ALEJANDRA_GIT_REF=4.0.0
ALEJANDRA_CARGO_PACKAGE=alejandra_cli
DEADNIX_GIT_URL=https://github.com/astro/deadnix
DEADNIX_GIT_REF=v1.3.1
DEADNIX_CARGO_PACKAGE=deadnix
STATIX_GIT_URL=https://github.com/oppiliappan/statix
STATIX_GIT_REF=v0.5.8
STATIX_CARGO_PACKAGE=statix

PYTHON_MDFORMAT_VERSION=0.7.22
PYTHON_MDFORMAT_GFM_VERSION=0.3.6
PYTHON_MDFORMAT_FRONTMATTER_VERSION=2.0.8
MARKDOWNLINT_CLI_VERSION=0.46.0

RUSTUP_VERSION=1.28.2
RUST_TOOLCHAIN_VERSION=1.87.0

MAX_FILE_SIZE_BYTES=512000

export TOOLS_MANIFEST_VERSION
export SHELLCHECK_VERSION
export JQ_VERSION
export YQ_VERSION
export GOLANGCI_LINT_VERSION
export STATICCHECK_VERSION
export REVIVE_VERSION
export GOLINES_VERSION
export ACTIONLINT_VERSION
export SHFMT_VERSION
export ALEJANDRA_GIT_URL
export ALEJANDRA_GIT_REF
export ALEJANDRA_CARGO_PACKAGE
export DEADNIX_GIT_URL
export DEADNIX_GIT_REF
export DEADNIX_CARGO_PACKAGE
export STATIX_GIT_URL
export STATIX_GIT_REF
export STATIX_CARGO_PACKAGE
export PYTHON_MDFORMAT_VERSION
export PYTHON_MDFORMAT_GFM_VERSION
export PYTHON_MDFORMAT_FRONTMATTER_VERSION
export MARKDOWNLINT_CLI_VERSION
export RUSTUP_VERSION
export RUST_TOOLCHAIN_VERSION
export MAX_FILE_SIZE_BYTES
