#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

ensure_repo_root

managed_marker="q15-managed-hook"
legacy_marker="File generated by prek"

remove_if_managed() {
	local hook_path="$1"

	[[ -e ${hook_path} ]] || return 0
	if grep -q "${managed_marker}" "${hook_path}" || grep -q "${legacy_marker}" "${hook_path}"; then
		rm -f "${hook_path}"
	fi
}

remove_if_managed "${REPO_ROOT}/.git/hooks/pre-commit"
remove_if_managed "${REPO_ROOT}/.git/hooks/pre-push"

log "removed q15-managed git hooks"
